repos:
  - repo: local
    hooks:

      - id: black
        name: black
        entry: black --config ./.black .
        language: system
        types: [python]

      - id: flake8
        name: flake8
        entry: flake8 --config .flake8 .
        language: system
        types: [python]
